### ISSUE TITLE
DApp execution to REVERT due to uncaught EXCEPTION: "null"

### ISSUE THREAD

**Issue by fulldecent** [fulldecent/aion-aip040#39]
Errors like this are seen in the build output and they add no value:

```
UnreachableMethodRemover crashed, packaging code without this optimization
DApp execution to REVERT due to uncaught EXCEPTION: "null"
i.RevertException
	at org.aion.avm.core.BlockchainRuntimeImpl.avm_require(BlockchainRuntimeImpl.java:407)
	at p.avm.Blockchain.avm_require(Blockchain.java:228)
	at org.aion.NFToken.avm_aip040OwnerDoesAuthorize(Unknown Source)
	at org.aion.Main.avm_aip040OwnerDoesAuthorize(Unknown Source)
	at org.aion.Main.avm_main(Unknown Source)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.aion.avm.core.persistence.LoadedDApp.callMain(LoadedDApp.java:246)
	at org.aion.avm.core.DAppExecutor.call(DAppExecutor.java:85)
	at org.aion.avm.core.AvmImpl.commonInvoke(AvmImpl.java:476)
	at org.aion.avm.core.AvmImpl.runExternalInvoke(AvmImpl.java:340)
	at org.aion.avm.core.AvmImpl.backgroundProcessTransaction(AvmImpl.java:242)
	at org.aion.avm.core.AvmImpl.access$300(AvmImpl.java:32)
	at org.aion.avm.core.AvmImpl$AvmExecutorThread.run(AvmImpl.java:97)
```

**Comment by fulldecent** [comment]
Hello @satran004, would you please be able to provide any advice here?

**Comment by jennijuju** [comment]
It's not a mvn thing - it's from avmrule. Error msgs will not be printed out if you turn off debug mode:
`public AvmRule avmRule = new AvmRule(false);`
